version: 2

workflows:
  version: 2
  build_and_test:
    jobs:
      - s/go-mod
      - s/go-get
      - c/py
      - c/py36

jobs:
  s/go-mod:
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - run:
          command: |
            cd server/go/thegame
            go build
            go test
  s/go-get:
    docker:
      - image: circleci/golang:1.11
    steps:
      - run: go get github.com/afg984/thegame/server/go/thegame
      - run: go test github.com/afg984/thegame/server/go/thegame
  c/py: &build_server_py_template
    working_directory: ~/thegame
    docker:
      - image: circleci/python:3.7
    steps:
      - run: python -m pip install --user git+https://github.com/afg984/thegame.git#subdirectory=client/python
  c/py36:
    <<: *build_server_py_template
    docker:
      - image: circleci/python:3.6
